sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install flake8"
script:
  - trial telegram
  - flake8 telegram
after_success:
  - coveralls
