sudo: false
language: python
python:
  - "2.7"
matrix:
  include:
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - python: "pypy"
      env: NO_COVERAGE=1
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install flake8"
script:
  - if [ -z "$NO_COVERAGE" ]; then COVERAGE_CMD="coverage run --source=telegram"; else COVERAGE_CMD=""; fi
  - flake8 telegram
  - VUMITEST_REDIS_DB=1 $COVERAGE_CMD `which trial` telegram

after_success:
  - if [ -z "$NO_COVERAGE" ]; then coveralls; fi
